// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/50387d40462301d54cda62e24d3b2ee46540f24a/gulp-watch/index.d.ts
declare module 'gulp-watch' {
// Type definitions for gulp-watch v4.1.1
// Project: https://github.com/floatdrop/gulp-watch
// Definitions by: Tanguy Krotoff <https://github.com/tkrotoff>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="node" />


interface IOptions {
    ignoreInitial?: boolean;
    events?: Array<string>;
    base?: string;
    name?: string;
    verbose?: boolean;
    readDelay?: number;
}

interface IWatchStream extends NodeJS.ReadWriteStream {
    add(path: string | Array<string>): NodeJS.ReadWriteStream;
    unwatch(path: string | Array<string>): NodeJS.ReadWriteStream;
    close(): NodeJS.ReadWriteStream;
}

function watch(glob: string | Array<string>, options?: IOptions, callback?: Function): IWatchStream;
namespace watch { }
export = watch;
}
