// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/50387d40462301d54cda62e24d3b2ee46540f24a/gulp-minify-css/index.d.ts
declare module 'gulp-minify-css' {
// Type definitions for gulp-minify-css
// Project: https://github.com/jonathanepollack/gulp-minify-css
// Definitions by: Keita Kagurazaka <https://github.com/k-kagurazaka>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="node" />

import * as CleanCSS from 'clean-css';

function minifyCSS(options?: CleanCSS.Options): NodeJS.ReadWriteStream;

namespace minifyCSS { }

export = minifyCSS;
}
